mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import Home, Base, Team, Landingpage
from videos.views import VideoListView
from videos.views import (
    VideoDetailView ,
    VideoCreateView ,
    VideoUpdateView ,
    VideoDeleteView ,
)

from .views import UsercreateView , UserCreateDoneView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UsercreateView.as_view(), name='register'),
    url(r'^accounts/register/done', UserCreateDoneView.as_view(), name='register_done' ),
    url(r'^$', Home.as_view()),
    url(r'^base/$', Base.as_view()),
    url(r'^team/$', Team.as_view()),
    url(r'^videos/$', VideoListView.as_view(), name='videos'),
    url(r'^videos/(?P<pk>\d+)/$', VideoDetailView.as_view(), name='video-detail'),
    url(r'^videos/create/$', VideoCreateView.as_view(), name='video-create'),
    url(r'^videos/(?P<pk>\d+)/update/$', VideoUpdateView.as_view(), name='video-update'),
    url(r'^videos/(?P<pk>\d+)/delete/$', VideoDeleteView.as_view(), name='video-delete'),
    url(r'^index/$', Landingpage.as_view(), name='Landingpage'),
    url(r'^photo/', include('photo.urls', namespace='photo')),
]

photo/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import url,static

from .views import (
    PhotoListView,
    PhotoDetailView,
)

urlpatterns = [
    url(r'^$', PhotoListView.as_view(), name='list'),
    url(r'^/(?P<pk>\d+)/$', PhotoDetailView.as_view(), name='detail'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/models.py
from django.db import models
from django.core.urlresolvers import reverse
from .fields import ThumbnailImageField

# Create your models here.
class Photo(models.Model):
    title = models.CharField(max_length=120)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('photo Description', blank=True)
    timestamp = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:detail', args=(self.id,))

videos/models.py
from django.db import models

# Create your models here.

class Video(models.Model):
    title = models.CharField(max_length=120)
    embed_code = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return '/videos/'

photo/forms.py
from django import forms

from .models import Photo

class PhotoForm(forms.ModelForm):
    class Meta:
        model = PhotoForm
        fields = ['title','image','description']

videos/forms.py
from django import forms

from .models import Video

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title','embed_code']

mysite/views.py
from django.views.generic import View
from django.shortcuts import render
from django.views.generic import TemplateView , CreateView
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy

class Home(View):
    def get(self, request, *args, **kwargs):
        context = {
            "name" :"John"
        }
        return render(request,"home.html", context )

class Base(View):
    def get(self, request, *args, **kwargs):
        return render(request,"base.html", { } )

class Team(View):
    def get(self, request, *args, **kwargs):
        return render(request,"team.html", { } )

class Landingpage(View):
    def get(self, request, *args, **kwargs):
        return render(request, "landingpage.html", { } )

class UsercreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneView(TemplateView):
    template_name = 'registration/register_done.html'

photo/views.py
from django.shortcuts import render

from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import Photo
from .forms import PhotoForm

# Create your views here.

class PhotoListView(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

class PhotoDetailView(DetailView):
    model = Photo
    template_name = 'photo/photo_detail.html'

class PhotoCreateView(CreateView):
    model = Photo
    template_name = 'photo/photo_create.html'

class PhotoCreateView(CreateView):
        model = Photo
        template_name = 'photo/photo_create.html'
        form_class = PhotoForm

videos/views.py
from django.shortcuts import render

# Create your views here.
from .models import Video
from django.views.generic import ListView
from django.views.generic import (
    DetailView ,
    CreateView ,
    UpdateView ,
    DeleteView
)
from .forms import VideoForm

class VideoListView(ListView):
    queryset = Video.objects.all()

    def get_context_data(self,*args, **kwargs):
        context = super(VideoListView,self).get_context_data(*args, **kwargs)
        context['all_count'] = Video.objects.all().count()
        return context

class VideoDetailView(DetailView):
    queryset = Video.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(VideoDetailView, self).get_context_data(*args , **kwargs)
        return context

class VideoCreateView(CreateView):
    model = Video
    form_class = VideoForm
    success_url = '/videos/'

    def form_valid(self, form):
        print('form_valid')
        print(self.request.POST.get('title'))
        print(self.request.POST.get('embed_code'))
        return super(VideoCreateView, self).form_valid(form)

    def form_invalid(self, form):
        print('form_in_valid')
        print(self.request.POST.get('title'))
        print(self.request.POST.get('embed_code'))
        pass

class VideoUpdateView(UpdateView):
    model = Video
    form_class = VideoForm

class VideoDeleteView(DeleteView):
    queryset = Video.objects.all()
    success_url = '/videos/'

templates/Team.html
{% extends "base.html" %}

{% block title %} Team {% endblock %}

{% block sidebar %}
    <ul>
        <li><a href="/">홈</a></li>
        <li><a href="/team/">팀명</a></li>
        <li>팀인원</li>
    </ul>
{% endblock sidebar %}

{% block content %}
<h1>팀은 우수한 팀입니다.</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>{% block title %}Base {% endblock %}</title>

<!-- google web font -->
<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i" rel="stylesheet">

<!--bootstrap -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">


</head>
<body>

{% block login %}
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                {% if user.is_active %}
                    <a href="{% url 'password_change' %}">비밀번호 변경</a>
                    <a href="{% url 'logout' %}">로그아웃</a>
                {% else %}
                    <a href="{% url 'login' %}">로그인</a>
                    <a href="{% url 'register' %}">회원가입</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

<div class="container">
    <div class="row">

        <div class="col-md-2">
            {% block sidebar %}
               <ul>
                   <li><a href="/">홈</a></li>
                   <li><a href="{% url 'videos' %}">동영상</a></li>
                   <li><a href="/index/">Landingpage</a></li>
                   <li><a href="/photo/">포토</a></li>
               </ul>
            {% endblock %}
        </div>
        <div class="col-md-10">
            {% block content %}
            <h1>base.html 입니다.</h1>
            {% endblock content %}

        </div>

    </div>
</div>


<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- bootstrap javascript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" ></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" ></script>
</body>
</html>

templates/defaults/head.html
{% load static %}

    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <!-- google web font -->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i" rel="stylesheet">
    <!-- font awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}">
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <!-- animate css-->
    <link rel="stylesheet" href="{% static 'css/animate/animate.css' %}">
    <!-- magnific-popup css -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup/magnific-popup.css' %}">
    <!-- owl-carousel css -->
    <link rel="stylesheet" href="{% static 'css/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl-carousel/owl.theme.default.css' %}">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<!-- animated   rotateInDownLeft , lightSpeedIn , slideInDown ,hinge , flip, bounceIn-->

templates/defaults/scripts.html
{% load static %}
<!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <!-- animate JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    <!-- bootstrap javascript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <!-- wow JS -->
    <script src="{% static 'js/wow/wow.min.js' %}"></script>
    <!-- magnific-popup js -->
    <script src="{% static 'js/magnific-popup/jquery.magnific-popup.min.js' %}"></script>
    <!-- counterup JS -->
    <script src="{% static 'js/counter/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/counter/jquery.counterup.min.js' %}"></script>
    <!-- custom javascript -->
    <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
    <!-- owl-carousel -->
    <script src="{% static 'js/owl-carousel/owl.carousel.min.js' %}"></script>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %} Home {% endblock %}

{% block content %}
<h1>Welcome to Home </h1>

<h3>
    안녕하세요

</h3>

<img src="{% static 'img/work/1.jpg' %}">

{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="kr">
<head>
       <meta charset ="UTF-8">
       <meta http-equiv = "X-UA-Compatible" content="IE=edge">
       <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %}Modern Responsive Website{% endblock %}</title>

    {% include 'defaults/head.html' %}

</head>
<body>
<!-- Menu -->
<header>
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <a class="navbar-brand" href="#"><img src="{% static 'img/logo.png' %}"></a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                     <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item">
                     <a class="nav-link" href="#services">Services</a>
                </li>
                <li class="nav-item">
                     <a class="nav-link" href="#about">About</a>
                </li>
                <li class="nav-item">
                     <a class="nav-link" href="#work">Work</a>
                </li>
                <li class="nav-item">
                     <a class="nav-link" href="#team">Team</a>
                </li>
                <li class="nav-item">
                     <a class="nav-link" href="#testimonials">Testimonials</a>
                </li>
                <li class="nav-item">
                     <a class="nav-link" href="#pricing">Pricing</a>
                </li>
                <li class="nav-item">
                     <a class="nav-link" href="#stats">Stat</a>
                </li>
                <li class="nav-item">
                     <a class="nav-link" href="#clients">Clients</a>
                </li>
                <li class="nav-item">
                     <a class="nav-link" href="#contact">Contact</a>
                </li>
                <li class="nav-item">
                     <a class="nav-link" href="/videos/">Videos</a>
                </li>


            </ul>
        </div>
    </nav>
</header>
{% block content %}

{% endblock %}
  {% include 'defaults/scripts.html' %}
</body>
</html>

templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/origin.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Home</title>

<!-- google web font -->
<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i" rel="stylesheet">

<!--bootstrap -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">


</head>
<body>




<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- bootstrap javascript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" ></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" ></script>
</body>
</html>

templates/photo/photo_detail.html
{% extends 'base.html'%}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <form>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Title</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" value="{{ object.title }}" disabled>
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Image</label>
    <div class="col-sm-6">
        <img class="img-fluid" src="{{ object.image.url }}">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-8 text-center">
      <button type="submit" class="btn btn-primary">Sign in</button>
        <a href=""
    </div>
  </div>
</form>
            </div>
        </div>
    </div>
{% endblock %}

templates/photo/photo_list.html
{% extends 'base.html'%}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Image</th>
                        <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in object_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></td>
                        <td><img class="img-fluid img-thumbnail" src="{{ item.image.thumb_url }}"></td>
                        <td>{{ item.timestamp|date:"Y-m-d-f" }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

templates/videos/video_confirm_delete.html
{% extends "base.html" %}


{% block content %}

<br><br>


    <form method="post" action="">
        {% csrf_token %}
        <p class="h2">죵말 삭제하시겠습니깕?</p>
        <br><br>
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'video-detail' object.id %}" class="btn btn-secondary" role="button">Cancel</a>
    </form>

{% endblock %}

templates/videos/video_detail.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col text-center">

        {{ object.title}} <br>
        {{ object.embed_code|safe }}

            <br><br>
            <a href="{% url 'video-update' object.id %}" class="btn btn-primary" role="button">Update</a>
            <a href="{% url 'video-delete' object.id %}" class="btn btn-danger" role="button">Delete</a>
            <br><br>
        <a href="javascript:history.back()" class="btn btn-secondary" role="button" >Back</a>

        </div>
    </div>

</div>


{% endblock %}

templates/videos/video_form.html
{% extends 'base.html' %}

    {% block content %}


<br><br>

<form method="post" action="">
    {% csrf_token %}
  <div class="form-group row">
    <label for="id_title" class="col-sm-2 col-form-label">Title:</label>
    <div class="col-sm-8">
      <input type="text" class="form-control" id="id_title" name="title" placeholder="타이틀을 입력하세요">
    </div>
  </div>
  <div class="form-group row">
    <label for="id_embed_code" class="col-sm-2 col-form-label">Embed code:</label>
    <div class="col-sm-8">
        <textarea cols="40" class="form-control" id="1d_embed_code" name="embed_code" rows="4"
                  placeholder="비디오 경로를 입력하세요" required></textarea>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10 text-center">
      <button type="submit" class="btn btn-primary">OK</button>
        <a href="javascript:history.back()" class="btn btn-secondary" role="button" >Back</a>
    </div>
  </div>
</form>

    {% endblock %}

templates/videos/video_list.html
{% extends "base.html" %}


{% block content %}

<br>
<a href="{% url 'video-create' %}" class="btn btn-primary" role="button">비디오 생성</a>
<br><br>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <!--<th scope="col" class="text-center">비디오 1</th>-->
      <!--<th scope="col" class="text-center">비디오 2</th>-->
      <!--<th scope="col" class="text-center">비디오 3</th>-->
      <th colspan="4" scope="col" class="text-center">
          총 비디오 {{all_count}}
      </th>
    </tr>
  </thead>
  <tbody>

    {% for object in object_list %}

            <tr>
              <!--{{object.embed_code|safe}} <br>-->
                <td><a href="{% url 'video-detail' object.id %}">{{object.title}}</a></td>
                <td>{{object.timestamp|date:"Y-m-d (H:i:s)[f:s]" }}</td>
                <td><a href="{% url 'video-update' object.id %}" class="btn btn-primary" role="button">Update</a></td>
                <td><a href="{% url 'video-delete' object.id %}" class="btn btn-danger" role="button">Delete</a></td>
            </tr>

    {% endfor %}
  </tbody>
</table>

{% endblock %}}